# SIADS 502: Math Methods for Data Science 


# School of Information, University of Michigan


## Practice Problem Set

### Version 1.1

This assignment aims to acquant you with both the autograder and Python's Numpy package. 

The assignment is optional and its grade will not impact your course grade.  

You can directly run each cell or write your own code to play around with them. For more detailed information on how to use Numpy, you can google or refer to this Numpy User Guide.  If you get stuck, please message on slack.  If you are really stuck, the answers are at the end.  However, also use this as a learning opportunity.

For the autograder:

*   Please remember to comment or delete raise NotImplementedError() in each cell. This error is just used to remind you there is a problem you need to finish and to distriguish between incorrect answers and those not completed.

*   In order to help you check your answers, we will have several public test cases. Validating your assignment will make sure your answers pass them.  

*  The autograder will also have hidden test cases.  Submit the assignment to rn them.  If you fail those cases, you will lose points on this assignment (but you can try each assignment as many times as you like---and, in any event, this assignment does not count).





Please enter your name: "Varshini"

## Part 1: Trial Exercises

<strong>1.1</strong> \[1 pt\] Import numpy package as np and check the version.

In [1]:
import numpy as np

# your code here
# HINT: import numpy as np
print(np.__version__)

# raise NotImplementedError() #Remember to comment this line to avoid any error message

# YOUR CODE HERE
# raise NotImplementedError()

1.20.3


In [2]:
assert np.__version__, True
# No hidden tests

<strong>1.2</strong> \[1 pt\] Create a 2-D vector  $v_a=(5,4)$  using numpy array and store it in variable <strong>ANS12</strong>.

In [10]:
ANS12 = np.array([5,4])
ANS12

# YOUR CODE HERE
# raise NotImplementedError()

array([5, 4])

In [11]:
ANS12.ndim

1

In [13]:
len(ANS12)

2

In [14]:
ANS12.shape

(2,)

In [12]:
import numbers

assert type(ANS12) == np.ndarray, "Problem 1.2, testing ANS12, type of value stored in variable does not match the expected type. Expecting numpy array."
assert len(ANS12) == 2, "Problem 1.2, testing ANS12, variable does not match the expected length. "
assert ANS12.shape == (2,), "Problem 1.2, testing ANS12, variable does not match the expected shape. "

assert isinstance(ANS12[0], numbers.Number) and isinstance(ANS12[1], numbers.Number),  "Problem 1.2, testing ANS12, type of values stored in array do not match the expected type.  Expecting float. "

<strong>1.3</strong> \[1 pt\] Predict what the following code will output and why:
    
$np.sqrt(6) * np.sqrt(24) == 12$
    
Store your result in <strong>ANS13</strong>.


In [43]:
import math

In [44]:
operation=math.sqrt(6)*math.sqrt(24)==12
operation

False

In [45]:
ANS13=operation
# YOUR CODE HERE
# raise NotImplementedError()

In [46]:
ANS13

False

In [47]:
type(ANS13)

bool

In [48]:
assert type(ANS13) == bool, "Problem 1.3, testing ANS13, type of value stored in variable does not match the expected type. Expecting bool."

<strong>1.4</strong> \[1 pt\] Create a numpy array for the 3*3 matrix $\left( \begin{array}{ccc} 0 & 1 & 2 \\ 3 & 4 & 5 \\ 6 & 7 & 8 \end{array} \right)$  in the variable $ANS14$.



In [49]:
ANS14=np.array([[0,1,2],[3,4,5],[6,7,8]])
# YOUR CODE HERE
# raise NotImplementedError()
ANS14

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
assert type(ANS14) == np.ndarray, "Problem 1.3, testing ANS14, type of value stored in variable does not match the expected type. Expecting numpy array."
assert ANS14.shape == (3, 3), "Problem 1.3, testing ANS14, array is not the correct shaps. "
assert isinstance(ANS14[0, 0], numbers.Number),  "Problem 1.3, testing ANS14, type of values stored in tuple do not match the expected type.  Expecting float. "

<strong>1.5</strong> \[1 pt\] Write a function $twos$ that takes two variables $a$ and $b$ and createx an $a$ x $b$ numpy array full of 2s;

In [51]:
def twos(a, b):
#     raise NotImplementedError()
    arr=np.full((a, b), 2)
    return arr
# YOUR CODE HERE
# raise NotImplementedError()

In [52]:
assert type(twos(2, 3)) == np.ndarray,  "Problem 1.5, testing twos, type of value stored in variable does not match the expected type. Expecting numpy array."
assert twos(2, 3).shape == (2, 3),  "Problem 1.5, testing twos, dimension of returned array is incorrect."
assert np.min(twos(2, 3)) == 2,  "Problem 1.5, resulting twos contains some number less than 2."
assert np.max(twos(2, 3)) == 2,  "Problem 1.5, resulting matrix contains some number greater than 2."


<strong>1.6</strong> \[1 pt\] Write a function <strong>add</strong> that takes two variables $a$ and $b$ that are both numpy arrays and adds them together. 

In [53]:
def add(a, b):
# YOUR CODE HERE
    arr=np.add(a, b)
    return arr
# raise NotImplementedError()

In [54]:
assert np.isclose(add(np.array([3, 4]), np.array([4, 3])), np.array([7, 7])).all(),  "Problem 1.6, returned value does not match expected value."


<strong>1.7</strong> \[1 pt\] Assume $A = \left( \begin{array}{cc} -2 & 6 \\ 1 & 4 \end{array} \right)$  and  $B = \left( \begin{array}{cc} 8 & -3 \\ 8 & -2 \end{array} \right)$. What are the sum and product of $A$ and $B$.   Please store your answers into a variable <strong>ANS16</strong> formatted as a dictionary that has two keys called "sum" and "product".


In [55]:
a=np.array([[-2,6],[1,4]])
b=np.array([[8,-3],[8,-2]])

In [56]:
ab_sum=np.add(a,b)
ab_prod=np.dot(a,b)

In [57]:
ab_sum

array([[6, 3],
       [9, 2]])

In [59]:
ab_prod

array([[ 32,  -6],
       [ 40, -11]])

In [61]:
ANS17={}
ANS17["sum"]=ab_sum
ANS17["product"]=ab_prod
# YOUR CODE HERE
# raise NotImplementedError()

In [62]:
ANS17

{'sum': array([[6, 3],
        [9, 2]]),
 'product': array([[ 32,  -6],
        [ 40, -11]])}

In [63]:
assert type(ANS17) == type({}), "Problem 1.7, testing ANS16, value stored in variable does not match the expected type. Expecting Dictionary."


<strong>1.8</strong> \[2 pt\]  Let  $F = \left( \begin{array}{ccc} 4 & 5 & c \\ 2 & 4 & b \\ 1 & 2 & a + b \end{array} \right)$ and $G= \left( \begin{array}{ccc} 4 & 2 & -b \\ 5 & 6 + c & 0  \\ 4 & 3 & a \end{array} \right)$  where $a$, $b$, and $c$ are variables. 

What is the trace of the matrix $F \cdot  G$?    Please store your answers into a string variable <strong>Trace_FG</strong>  written with valid python code formatting (e.g. Trace_FG = "2 + a -b"). (Note you are encouraged to do this by hand.)

Hint:  If you don't pass the test.  Set $a$, $b$, and $c$ to zero.  Then you can use the python eval function to check your answer.  For example: Run


$a = 0$ <br> 
$b = 0$ <br> 
$c = 0$ <br> 
$eval(Trace\_FG)$

Then run 

$F = np.array([[4, 5, c], [2, 4, b], [1, 2, a + b]])$  <br> 
$G = np.array([[4,2, -b],[5,6+𝑐,0],[4,3,a]])$ <br> 
$np.trace(F@G)$

The results should match.  If not, you got one of the constant terms of the answer incorrect.  Try running: 

F@G and make sure you computed the constant terms of the matrix product correctly.

Once your answer matches for $a = b = c = 0$.  Try changing $a = 1$ and check if you correctly computed the a terms.  Then reset $a = 0$, but let $b = 1$.   Etc.

This will allow you to track down arithmetic errors without simply computing the entire quantity again.  


In [75]:
Trace_FG="69 + a*a + a*b + 8*c + 2*b"
# YOUR CODE HERE
# raise NotImplementedError()


In [76]:
assert type(Trace_FG) == str, "Problem 1.7, type of value stored in variable Trace_FG does not match the expected type."

## Answers

In [ ]:
ANS12 = np.array((5,4))

ANS13 = False; there are rounding errors in the calculation

ANS14 = np.array(range(9)).reshape(3, 3)

def ones(a, b):
    return 2* np.ones((a, b))

def add(a, b):
    return a + b

ANS61 = {'sum': np.array([[6, 3], [9, 2]]), 'product': np.array([[ 32,  -6], [ 40, -11]])}

Trace_FG = "69 + a*a + a*b + 8*c + 2*b"